# Generated by Django 4.2.7 on 2023-11-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="latitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sensordata",
            name="longitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
