# Generated by Django 4.2.7 on 2023-11-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_sensordata_latitude_sensordata_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="sensor_id",
            field=models.CharField(
                help_text="The sensor ID", max_length=255, null=True
            ),
        ),
    ]
