# Generated by Django 4.2.7 on 2023-11-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_sensordata_sensor_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensordata",
            name="pressure",
        ),
        migrations.RemoveField(
            model_name="sensordata",
            name="steam_injection",
        ),
        migrations.RemoveField(
            model_name="sensordata",
            name="temperature",
        ),
        migrations.AddField(
            model_name="sensordata",
            name="type",
            field=models.CharField(
                choices=[
                    ("temperature", "Temperature"),
                    ("pressure", "Pressure"),
                    ("steam_injection", "Steam Injection"),
                ],
                default="temperature",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sensordata",
            name="value",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
